### ISSUE TITLE
Dealing with duplicate provence entries

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/pyslim#67] opened 2020-02-27 13:44 UTC
I'm doing SLiM simulations with selection, calling `sim.treeSeqOutput()` before the mutation is introduced, and then rewinding/restoring with `sim.readFromPopulationFile()` if the mutation is lost. Actually, I 'save' the state with `sim.readFromPopulationFile()` again when the mutation is transferred to another population via migration. So I can end up with multiple SLiM provenance entries. Only the last one is really useful.

Currently, I'm using the following function to remove the redundant entries. Is there a more appropriate way? Would this function be useful to include in pyslim?
```python
def dedup_slim_provenances(ts):
    """
    Remove redundant copies of SLiM's provenance records.

    Duplicate SLiM provenance records may result from sim.treeSeqOutput()
    followed by sim.readFromPopulationFile(), as is common when ensuring that
    an introduced mutation is not lost.
    """
    tables = ts.dump_tables()
    tables.provenances.clear()

    # Find the last SLiM provenance entry.
    i = -1
    for p in ts.provenances():
        d = json.loads(p.record)
        if d["software"]["name"] == "SLiM":
            i += 1
    assert i >= 0, "SLiM provenance not found"

    for j, p in enumerate(ts.provenances()):
        if j < i:
            continue
        tables.provenances.add_row(p.record, p.timestamp)

    return tables.tree_sequence()
```

**Comment by jeromekelleher** [comment] 2020-02-28 10:14
Is there an option to say "don't store provenance"? This would stop the unused provenance being stored in the first place. (This is supported in some tskit functions, and should be an option in msprime too.)

**Comment by grahamgower** [comment] 2020-02-28 10:22
I don't see any such option to `sim.treeSeqOutput()` in the SLiM manual. Certainly it would be a nicer solution to add that, if possible. But maybe various provenance metadata is needed when loading again from a tree sequence?

**Comment by grahamgower** [comment] 2020-02-28 15:13
SLiM reads the generation number from the provenance info, which seems rather essential.
https://github.com/MesserLab/SLiM/blob/7e343c4fdff7e210f9cf06ac0d3e902d76855cb6/core/slim_sim.cpp#L7879

**Comment by petrelharp** [comment] 2020-02-28 15:30
Hm - could you explain more? Having multiple provinance entries - in general - is good, if the ts has been produced using multiple stages of slim simulation. What's the bad thing that's happening here? You're not getting an extra provenance per rewind-and-replay, are you?

**Comment by grahamgower** [comment] 2020-02-28 15:35
No, not per rewind-and-replay, just for each call to sim.treeSeqOutput(). The only thing different between the provenance entries is the recorded generation. Including the same slim script in each provenance entry seems quite redundant.

**Comment by jeromekelleher** [comment] 2020-02-28 16:42
Unless there's hundreds of entries I'd be with @petrelharp here and not worry about it. But I still think it's good to have the option of not storing provenance. Sometimes is just doesn't matter. SLiM is using the provenance information as a way of storing metadata (the generation number), which is bad I think (provenance is supposed to be about how it was made, not what it is). There's currently no option though, since we don't have a way of associating metadata with a tree sequence right now. Hopefully this'll be fixed soon.

Anyway, that's off topic.

**Comment by petrelharp** [comment] 2020-02-28 16:44
Hm, ok, but I vote for *not* even making it an option to not store provenance, unless we have a use case where it's a problem. We want to encourage people to have reproducible pipelines, and storing the provenance each time, even if it's just "I ran the same script again" is good practice. Since: what if you *think* it was the same script, but whoops - you changed something?

**Comment by jeromekelleher** [comment] 2020-02-28 16:48
Here's the use-case @petrelharp: https://github.com/popsim-consortium/stdpopsim/pull/412

We're already storing perfect provenance by recording the command line in stdpopsim, and we're potentially writing out megabytes of text to encode things like recombination maps.

**Comment by petrelharp** [comment] 2020-02-28 16:54
Ah, ok. I mean, what's a few extra tens of megabytes... but - what do you think, @bhaller? We should move this to SLiM if it's worth doing. The proposal would be - I think - when reloading from a tree sequence, provide an option to *not* keep the previous provenance entry, so when writing out the tree sequence again we would replace the previous one.

I would tend to want to store things like recombination maps as text files that get read in by SLiM, not directly in the script, but being self-contained is good...

**Comment by jeromekelleher** [comment] 2020-02-28 17:11
Well I'd suggest just having a switch saying "don't store provenance at all" which is an advanced feature for downstream application developers (like stdpopsim). The root problem here isn't storing copies of the provenance, it's storing it all. I understand that you guys are using the provenance to store essential stuff at the moment though, so until we have a ``TreeSequence.metadata`` field (which could be used for this essential stuff), it's possibly a little dangerous to add the option?

**Comment by petrelharp** [comment] 2020-02-28 17:16
> Well I'd suggest just having a switch saying "don't store provenance at all"

I agree - we should not do this until we have a way of reading back in the generation in some other way.

**Comment by bhaller** [comment] 2020-02-28 17:20
I think SLiM also uses the provenance to version-check the file, check that it is marked as having SLiM metadata, etc. (I'd have to check the code to be sure, which I don't have time to do right now, I'm on the road...), and some of that does seem to be a legitimate use of the provenance field itself; it has to do with "who made the file and what sort of file is it", which seems like provenance.  Do we really want to allow files that have no provenance info at all?  It seems like a virtue, not a vice, that treeseq files are always marked with their provenance.  It seems like the root problem here is maybe a little different – that the provenance information contains a copy of the script, _and_ that that script is so huge that it causes a problem.  Maybe what we really want in SLiM is a "don't write the script to the provenance" flag?  Although I agree that storing the generation number as treeseq metadata instead of in the provenance would also make sense; but even if that were now possible, I'm still not convinced that we would then want to support not writing out a provenance entry at all.  Feels like the wrong fix.

**Comment by petrelharp** [comment] 2020-02-28 18:05
> Maybe what we really want in SLiM is a "don't write the script to the provenance" flag?

That's a good solution - maybe there could be an option to write a *hash* of the script instead of the script itself.

**Comment by bhaller** [comment] 2020-03-02 17:20
If we are agreed that an optional flag for outputTreeSeq() in SLiM, telling SLiM to write out only a has of the script rather than the full script, is the correct solution, I can add that to SLiM any time, it's trivial.  Are we agreed?  What hash algorithm should be used?  Is there a standard one I should use?

**Comment by grahamgower** [comment] 2020-03-02 18:33
Thanks @bhaller, that would be a great addition. I'd recommend using SHA256. Anything that can also be run with ubiquitous command line tools should be fine though (sha256sum comes with GNU coreutils and is installed as standard on linux systems, but I don't know about mac). There are several standalone implementations you could use, e.g.
https://github.com/amosnier/sha-2
https://github.com/B-Con/crypto-algorithms

**Comment by petrelharp** [comment] 2020-03-02 18:43
We should move this over to the SLiM repo, I think.

**Comment by bhaller** [comment] 2020-03-19 15:30
@grahamgower Sorry for the delay, implementing this now.  I am inclined to put the human-readable hash into the provenance (e.g., "7fa3...") rather than the raw 256-bit hash data.  Do you agree?  @petrelharp @jeromekelleher any strong opinions?

**Comment by grahamgower** [comment] 2020-03-19 15:38
Thanks @bhaller. I think the best thing to do is use the string one gets when using the command line program. Eg.
```
$ echo foo  | sha256sum | awk '{print $1}'
b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
```
I guess this is also the human-readable hash?

**Comment by bhaller** [comment] 2020-03-19 15:54
Yep.

**Comment by bhaller** [comment] 2020-03-19 16:46
Hey @grahamgower, do you have a python script that takes a path to a .trees file and prints the provenance entries?  I could figure it out, but I'm not much good in Python, so it's easier to ask, since I imagine you already have this.  :->  Or @petrelharp?

**Comment by grahamgower** [comment] 2020-03-19 16:57
I believe `tskit provenances foo.trees` will do what you're after. You just need the tskit python package installed.

**Comment by bhaller** [comment] 2020-03-19 17:04
> I believe `tskit provenances foo.trees` will do what you're after. You just need the tskit python package installed.

@grahamgower, can you provide a usage example?  I'm mystified:

```% python3 tskit provenances /Users/bhaller/Desktop/recipe_17.1_foo.trees 
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'tskit': [Errno 2] No such file or directory```

```% python3
Python 3.6.10 (default, Dec 22 2019, 00:54:40) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tskit
>>> tskit provenances /Users/bhaller/Desktop/recipe_17.1_foo.trees
  File "<stdin>", line 1
    tskit provenances /Users/bhaller/Desktop/recipe_17.1_foo.trees
                    ^
SyntaxError: invalid syntax
>>> ```

When I say I'm not much good in python, I mean it.  ;->

**Comment by bhaller** [comment] 2020-03-19 17:06
Anyway, that aside.  OK folks.  I have added a new optional parameter, `[logical$ includeModel=T]`, to the `treeSeqOutput()` method; if it is `F`, the `model` key is now omitted from the provenance record.  I have also added a new subkey of `parameters`, named `model_hash`, that contains the lowercase-hexadecimal ASCII SHA-256 hash of the model script (i.e., the same format as produced by sha256sum); this new key is always written, regardless of the value of `includeModel`.  The `file_version` key has been incremented from `"0.3"` to `"0.4"`; this may (or may not) require a corresponding update on the `pyslim` side to avoid it throwing a "file version not recognized" type of error, I haven't tried (@petrelharp).  These changes are now committed to the master branch of SLiM.  If it seems good, and necessary changes on the pyslim side have been made, I think this issue can be closed.  Let me know if anything else is needed from my end.  :->

**Comment by jeromekelleher** [comment] 2020-03-19 17:24
``python3 -m tskit provenances foot.trees`` should do the trick @bhaller. Also, if you have your PATH set up properly, you should be able to call the ``tskit`` executable directly, like ``tskit provenances foot.trees``. 

The ``python3 -m tskit`` route will always work though.

**Comment by jeromekelleher** [comment] 2020-03-19 17:24
(Dunno why my fingers turn "foo" into "foot"...)

**Comment by bhaller** [comment] 2020-03-19 17:40
> `python3 -m tskit provenances foot.trees` should do the trick @bhaller. Also, if you have your PATH set up properly, you should be able to call the `tskit` executable directly, like `tskit provenances foot.trees`.
> 
> The `python3 -m tskit` route will always work though.

Got it, thanks!  The generated files look correct.

**Comment by jeromekelleher** [comment] 2020-03-19 17:51
A nice trick is to use jq. `` tskit provenances tmp.trees | tail -n 1 | cut -f3 | jq`` gives
```json
{
  "schema_version": "1.0.0",
  "software": {
    "name": "msprime",
    "version": "0.7.5.dev85+g2d7dab98"
  },
  "parameters": {
    "command": "simulate",
    "sample_size": 10,
    "Ne": 1,
    "length": 1,
    "recombination_rate": 0,
    "recombination_map": null,
    "mutation_rate": 0,
    "population_configurations": null,
    "pedigree": null,
    "migration_matrix": null,
    "demographic_events": [],
    "samples": null,
    "model": null,
    "record_migrations": false,
    "random_seed": 1123955094,
    "mutation_generator": null,
    "from_ts": null,
    "start_time": null,
    "end_time": null,
    "record_full_arg": false,
    "num_labels": null,
    "record_provenance": true,
    "gene_conversion_rate": null,
    "gene_conversion_track_length": null,
    "replicate_index": 0
  },
  "environment": {
    "os": {
      "system": "Linux",
      "node": "empire",
      "release": "4.15.0-91-generic",
      "version": "#92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020",
      "machine": "x86_64"
    },
    "python": {
      "implementation": "CPython",
      "version": "3.6.9"
    },
    "libraries": {
      "kastore": {
        "version": "1.0.0"
      },
      "tskit": {
        "version": "0.2.3"
      },
      "gsl": {
        "version": "2.4"
      }
    }
  }
}
```

**Comment by petrelharp** [comment] 2020-03-20 00:23
I will definitely need to upgrade pyslim for this. Perhaps it would have been better to do a coordinated "release"? (In quotes because you've just pushed to master, not done a release, but still, we tell people they can use master...)

I can do that next week but not now, apologies.

**Comment by bhaller** [comment] 2020-03-20 00:30
> I will definitely need to upgrade pyslim for this. Perhaps it would have been better to do a coordinated "release"? (In quotes because you've just pushed to master, not done a release, but still, we tell people they can use master...)
> 
> I can do that next week but not now, apologies.

It probably would have been better (I'll be more careful in future), but no worries; very little has changed on master since the 3.3.2 release, so I doubt this will affect anybody – I doubt anybody will try to use master in the next week.  I'm more careful when I know that there is an actual reason why somebody would be living on master; right now there isn't, except for one guy who has already updated to get the bug fix he needed.  If anybody contacts me about a problem I'll just tell them to use 3.3.2.

**Comment by petrelharp** [comment] 2020-03-25 17:01
Ok - I've updated pyslim, fixed a bug in msprime that affected us, and updated the version on PyPI. We should be good to go.

**Closed** 2020-03-26 22:47 UTC
